"""Bounded public surface for the virtual 100 USDT paper fund foundation.

Simulation only. REAL_CAPITAL remains 0. No real exchange order path.
"""

from crypto_signal.paper.autonomy import (
    PAPER_AUTONOMY_POLICY_VERSION,
    PaperAutonomyDecision,
    PaperAutonomyPolicy,
    PaperAutonomyReason,
    default_conservative_autonomy_policy,
    evaluate_autonomy_policy,
)
from crypto_signal.paper.commit import (
    PaperBundleCommitError,
    PaperBundleCommitResult,
    commit_orchestration_bundle,
)
from crypto_signal.paper.execution_input import (
    PAPER_EXECUTION_INPUT_POLICY_VERSION,
    FrozenPaperExecutionInput,
    PaperExecutionInputError,
    PaperExecutionInputResult,
    PaperExecutionInputStatus,
    freeze_execution_input_from_cache,
)
from crypto_signal.paper.ledger import (
    PaperFundLedger,
    PaperLedgerConflictError,
    PaperLedgerEntry,
    PaperLedgerWriteDisposition,
    PaperRecordKind,
)
from crypto_signal.paper.models import (
    BENCHMARK_IDS,
    INITIAL_CASH_USDT,
    PAPER_EXECUTION_POLICY_VERSION,
    PAPER_FUND_SCHEMA_VERSION,
    PAPER_RISK_POLICY_VERSION,
    PARTIAL_FILLS_SUPPORTED,
    PERMITTED_ACTIONS,
    PERMITTED_SYMBOLS,
    REAL_CAPITAL,
    BenchmarkId,
    DecisionIntentRecord,
    ExecutionCostAssumptions,
    FundCreationRecord,
    NavSnapshotRecord,
    PaperAction,
    PaperPosition,
    PaperSymbol,
    PositionCashMutationRecord,
    SimulatedFillRecord,
    build_decision_intent,
    build_fund_creation,
    build_nav_snapshot,
    build_position_cash_mutation,
    build_simulated_fill,
    initial_account_state,
)
from crypto_signal.paper.runtime import (
    PaperFundBootstrapStatus,
    PaperRuntimeError,
    PaperRuntimeSnapshot,
    PaperSignalLedgerObservation,
    ensure_persistent_paper_fund,
    observe_signal_ledger,
    run_paper_runtime_tick,
)

__all__ = [
    "BENCHMARK_IDS",
    "INITIAL_CASH_USDT",
    "PAPER_AUTONOMY_POLICY_VERSION",
    "PAPER_EXECUTION_INPUT_POLICY_VERSION",
    "PAPER_EXECUTION_POLICY_VERSION",
    "PAPER_FUND_SCHEMA_VERSION",
    "PAPER_RISK_POLICY_VERSION",
    "PARTIAL_FILLS_SUPPORTED",
    "PERMITTED_ACTIONS",
    "PERMITTED_SYMBOLS",
    "REAL_CAPITAL",
    "BenchmarkId",
    "DecisionIntentRecord",
    "ExecutionCostAssumptions",
    "FrozenPaperExecutionInput",
    "FundCreationRecord",
    "NavSnapshotRecord",
    "PaperAction",
    "PaperAutonomyDecision",
    "PaperAutonomyPolicy",
    "PaperAutonomyReason",
    "PaperBundleCommitError",
    "PaperBundleCommitResult",
    "PaperExecutionInputError",
    "PaperExecutionInputResult",
    "PaperExecutionInputStatus",
    "PaperFundBootstrapStatus",
    "PaperFundLedger",
    "PaperLedgerConflictError",
    "PaperLedgerEntry",
    "PaperLedgerWriteDisposition",
    "PaperPosition",
    "PaperRecordKind",
    "PaperRuntimeError",
    "PaperRuntimeSnapshot",
    "PaperSignalLedgerObservation",
    "PaperSymbol",
    "PositionCashMutationRecord",
    "SimulatedFillRecord",
    "build_decision_intent",
    "build_fund_creation",
    "build_nav_snapshot",
    "build_position_cash_mutation",
    "build_simulated_fill",
    "commit_orchestration_bundle",
    "default_conservative_autonomy_policy",
    "ensure_persistent_paper_fund",
    "evaluate_autonomy_policy",
    "freeze_execution_input_from_cache",
    "initial_account_state",
    "observe_signal_ledger",
    "run_paper_runtime_tick",
]
